### ISSUE TITLE
SwipeAction出现渲错误问题

### ISSUE THREAD

**Issue by LightHouseAC** [FirstUI/FirstUI-weixin#6]
<img width="408" alt="1679570517144" src="https://user-images.githubusercontent.com/103368875/227188758-69e528ca-3bd1-4d67-92d3-714c3875cdb4.png">
### 下面是代码，直接复制的示例
<img width="603" alt="1679570626588" src="https://user-images.githubusercontent.com/103368875/227189272-dff1afb1-17a2-4331-bdba-99f48258b9f7.png">
报错后，list-cell仍会显示，但是不能滑动操作

**Comment by FirstUI** [comment]
1、目前暂未复现此问题，看一下开发工具是否为最新版本、调试基础库是否为较新版本，更新到最新版本尝试一下
2、show传值为bool类型，使用{{true}}
3、如果不能解决，重新下载代码尝试
