### ISSUE TITLE
找不到对应的fui-form组件

### ISSUE THREAD

**Issue by xuzhiyong017** [FirstUI/FirstUI-weixin#7]
![image](https://github.com/FirstUI/FirstUI-weixin/assets/9525318/a7ea8dd3-f138-4c07-9f7e-153cae44dd02)
![image](https://github.com/FirstUI/FirstUI-weixin/assets/9525318/7039810a-5d87-4f78-b5fd-f6af75bcaa1e)

**Comment by FirstUI** [comment]
带V标识的为会员组件，非开源组件
